// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HubbleInitParameters struct {

	// (Boolean) Deploy Hubble Relay (Default: true).
	// Deploy Hubble Relay (Default: `true`).
	Relay *bool `json:"relay,omitempty" tf:"relay,omitempty"`

	// (Boolean) Enable Hubble UI (Default: false).
	// Enable Hubble UI (Default: `false`).
	UI *bool `json:"ui,omitempty" tf:"ui,omitempty"`
}

type HubbleObservation struct {

	// (String) Cilium hubble identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Deploy Hubble Relay (Default: true).
	// Deploy Hubble Relay (Default: `true`).
	Relay *bool `json:"relay,omitempty" tf:"relay,omitempty"`

	// (Boolean) Enable Hubble UI (Default: false).
	// Enable Hubble UI (Default: `false`).
	UI *bool `json:"ui,omitempty" tf:"ui,omitempty"`
}

type HubbleParameters struct {

	// (Boolean) Deploy Hubble Relay (Default: true).
	// Deploy Hubble Relay (Default: `true`).
	// +kubebuilder:validation:Optional
	Relay *bool `json:"relay,omitempty" tf:"relay,omitempty"`

	// (Boolean) Enable Hubble UI (Default: false).
	// Enable Hubble UI (Default: `false`).
	// +kubebuilder:validation:Optional
	UI *bool `json:"ui,omitempty" tf:"ui,omitempty"`
}

// HubbleSpec defines the desired state of Hubble
type HubbleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HubbleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HubbleInitParameters `json:"initProvider,omitempty"`
}

// HubbleStatus defines the observed state of Hubble.
type HubbleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HubbleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Hubble is the Schema for the Hubbles API. Hubble resource for Cilium. This is equivalent to cilium cli: cilium hubble: It manages cilium hubble
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cilium}
type Hubble struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              HubbleSpec   `json:"spec"`
	Status            HubbleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HubbleList contains a list of Hubbles
type HubbleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hubble `json:"items"`
}

// Repository type metadata.
var (
	Hubble_Kind             = "Hubble"
	Hubble_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Hubble_Kind}.String()
	Hubble_KindAPIVersion   = Hubble_Kind + "." + CRDGroupVersion.String()
	Hubble_GroupVersionKind = CRDGroupVersion.WithKind(Hubble_Kind)
)

func init() {
	SchemeBuilder.Register(&Hubble{}, &HubbleList{})
}
