//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeployment) DeepCopyInto(out *CiliumDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeployment.
func (in *CiliumDeployment) DeepCopy() *CiliumDeployment {
	if in == nil {
		return nil
	}
	out := new(CiliumDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentInitParameters) DeepCopyInto(out *CiliumDeploymentInitParameters) {
	*out = *in
	if in.DataPath != nil {
		in, out := &in.DataPath, &out.DataPath
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(bool)
		**out = **in
	}
	if in.Reuse != nil {
		in, out := &in.Reuse, &out.Reuse
		*out = new(bool)
		**out = **in
	}
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentInitParameters.
func (in *CiliumDeploymentInitParameters) DeepCopy() *CiliumDeploymentInitParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentList) DeepCopyInto(out *CiliumDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiliumDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentList.
func (in *CiliumDeploymentList) DeepCopy() *CiliumDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentObservation) DeepCopyInto(out *CiliumDeploymentObservation) {
	*out = *in
	if in.DataPath != nil {
		in, out := &in.DataPath, &out.DataPath
		*out = new(string)
		**out = **in
	}
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(bool)
		**out = **in
	}
	if in.Reuse != nil {
		in, out := &in.Reuse, &out.Reuse
		*out = new(bool)
		**out = **in
	}
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentObservation.
func (in *CiliumDeploymentObservation) DeepCopy() *CiliumDeploymentObservation {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentParameters) DeepCopyInto(out *CiliumDeploymentParameters) {
	*out = *in
	if in.DataPath != nil {
		in, out := &in.DataPath, &out.DataPath
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(bool)
		**out = **in
	}
	if in.Reuse != nil {
		in, out := &in.Reuse, &out.Reuse
		*out = new(bool)
		**out = **in
	}
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentParameters.
func (in *CiliumDeploymentParameters) DeepCopy() *CiliumDeploymentParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentSpec) DeepCopyInto(out *CiliumDeploymentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentSpec.
func (in *CiliumDeploymentSpec) DeepCopy() *CiliumDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumDeploymentStatus) DeepCopyInto(out *CiliumDeploymentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumDeploymentStatus.
func (in *CiliumDeploymentStatus) DeepCopy() *CiliumDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CiliumDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
