// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type KubeProxyFreeInitParameters struct {

	// Name of DaemonSet (Default: `kube-proxy`).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Namespace of DaemonSet (Default: `kube-system`).
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type KubeProxyFreeObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of DaemonSet (Default: `kube-proxy`).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Namespace of DaemonSet (Default: `kube-system`).
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type KubeProxyFreeParameters struct {

	// Name of DaemonSet (Default: `kube-proxy`).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Namespace of DaemonSet (Default: `kube-system`).
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

// KubeProxyFreeSpec defines the desired state of KubeProxyFree
type KubeProxyFreeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KubeProxyFreeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KubeProxyFreeInitParameters `json:"initProvider,omitempty"`
}

// KubeProxyFreeStatus defines the observed state of KubeProxyFree.
type KubeProxyFreeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KubeProxyFreeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// KubeProxyFree is the Schema for the KubeProxyFrees API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cilium}
type KubeProxyFree struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KubeProxyFreeSpec   `json:"spec"`
	Status            KubeProxyFreeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubeProxyFreeList contains a list of KubeProxyFrees
type KubeProxyFreeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KubeProxyFree `json:"items"`
}

// Repository type metadata.
var (
	KubeProxyFree_Kind             = "KubeProxyFree"
	KubeProxyFree_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KubeProxyFree_Kind}.String()
	KubeProxyFree_KindAPIVersion   = KubeProxyFree_Kind + "." + CRDGroupVersion.String()
	KubeProxyFree_GroupVersionKind = CRDGroupVersion.WithKind(KubeProxyFree_Kind)
)

func init() {
	SchemeBuilder.Register(&KubeProxyFree{}, &KubeProxyFreeList{})
}
