// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CiliumClusterMeshConnectionInitParameters struct {
}

type CiliumClusterMeshConnectionObservation struct {

	// (String) Kubernetes configuration context of destination cluster
	// Kubernetes configuration context of destination cluster
	DestinationContext *string `json:"destinationContext,omitempty" tf:"destination_context,omitempty"`

	// (String) Cilium ClusterMesh Connection identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type CiliumClusterMeshConnectionParameters struct {

	// (String) Kubernetes configuration context of destination cluster
	// Kubernetes configuration context of destination cluster
	// +kubebuilder:validation:Optional
	DestinationContext *string `json:"destinationContext,omitempty" tf:"destination_context,omitempty"`
}

// CiliumClusterMeshConnectionSpec defines the desired state of CiliumClusterMeshConnection
type CiliumClusterMeshConnectionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CiliumClusterMeshConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CiliumClusterMeshConnectionInitParameters `json:"initProvider,omitempty"`
}

// CiliumClusterMeshConnectionStatus defines the observed state of CiliumClusterMeshConnection.
type CiliumClusterMeshConnectionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CiliumClusterMeshConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// CiliumClusterMeshConnection is the Schema for the CiliumClusterMeshConnections API. Cluster Mesh connection resource. This is equivalent to cilium cli: cilium clustermesh connect and cilium clustermesh disconnect: It manages the connections between two Kubernetes clusters.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cilium}
type CiliumClusterMeshConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CiliumClusterMeshConnectionSpec   `json:"spec"`
	Status            CiliumClusterMeshConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CiliumClusterMeshConnectionList contains a list of CiliumClusterMeshConnections
type CiliumClusterMeshConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CiliumClusterMeshConnection `json:"items"`
}

// Repository type metadata.
var (
	CiliumClusterMeshConnection_Kind             = "CiliumClusterMeshConnection"
	CiliumClusterMeshConnection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CiliumClusterMeshConnection_Kind}.String()
	CiliumClusterMeshConnection_KindAPIVersion   = CiliumClusterMeshConnection_Kind + "." + CRDGroupVersion.String()
	CiliumClusterMeshConnection_GroupVersionKind = CRDGroupVersion.WithKind(CiliumClusterMeshConnection_Kind)
)

func init() {
	SchemeBuilder.Register(&CiliumClusterMeshConnection{}, &CiliumClusterMeshConnectionList{})
}
