// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/crossplane/upjet/pkg/resource"
	"github.com/crossplane/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this CiliumClusterMeshEnabler
func (mg *CiliumClusterMeshEnabler) GetTerraformResourceType() string {
	return "cilium_clustermesh"
}

// GetConnectionDetailsMapping for this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// GetInitParameters of this CiliumClusterMeshEnabler
func (tr *CiliumClusterMeshEnabler) GetInitParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.InitProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// LateInitialize this CiliumClusterMeshEnabler using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *CiliumClusterMeshEnabler) LateInitialize(attrs []byte) (bool, error) {
	params := &CiliumClusterMeshEnablerParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *CiliumClusterMeshEnabler) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this CiliumClusterMeshConnection
func (mg *CiliumClusterMeshConnection) GetTerraformResourceType() string {
	return "cilium_clustermesh_connection"
}

// GetConnectionDetailsMapping for this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// GetInitParameters of this CiliumClusterMeshConnection
func (tr *CiliumClusterMeshConnection) GetInitParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.InitProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// LateInitialize this CiliumClusterMeshConnection using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *CiliumClusterMeshConnection) LateInitialize(attrs []byte) (bool, error) {
	params := &CiliumClusterMeshConnectionParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *CiliumClusterMeshConnection) GetTerraformSchemaVersion() int {
	return 0
}
