/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetPublishConnectionDetailsTo of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetPublishConnectionDetailsTo of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this CiliumClusterMeshConnection.
func (mg *CiliumClusterMeshConnection) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetPublishConnectionDetailsTo of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetPublishConnectionDetailsTo of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this CiliumClusterMeshEnabler.
func (mg *CiliumClusterMeshEnabler) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
