//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnection) DeepCopyInto(out *CiliumClusterMeshConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnection.
func (in *CiliumClusterMeshConnection) DeepCopy() *CiliumClusterMeshConnection {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumClusterMeshConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionInitParameters) DeepCopyInto(out *CiliumClusterMeshConnectionInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionInitParameters.
func (in *CiliumClusterMeshConnectionInitParameters) DeepCopy() *CiliumClusterMeshConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionList) DeepCopyInto(out *CiliumClusterMeshConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiliumClusterMeshConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionList.
func (in *CiliumClusterMeshConnectionList) DeepCopy() *CiliumClusterMeshConnectionList {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumClusterMeshConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionObservation) DeepCopyInto(out *CiliumClusterMeshConnectionObservation) {
	*out = *in
	if in.DestinationContext != nil {
		in, out := &in.DestinationContext, &out.DestinationContext
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionObservation.
func (in *CiliumClusterMeshConnectionObservation) DeepCopy() *CiliumClusterMeshConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionParameters) DeepCopyInto(out *CiliumClusterMeshConnectionParameters) {
	*out = *in
	if in.DestinationContext != nil {
		in, out := &in.DestinationContext, &out.DestinationContext
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionParameters.
func (in *CiliumClusterMeshConnectionParameters) DeepCopy() *CiliumClusterMeshConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionSpec) DeepCopyInto(out *CiliumClusterMeshConnectionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	out.InitProvider = in.InitProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionSpec.
func (in *CiliumClusterMeshConnectionSpec) DeepCopy() *CiliumClusterMeshConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshConnectionStatus) DeepCopyInto(out *CiliumClusterMeshConnectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshConnectionStatus.
func (in *CiliumClusterMeshConnectionStatus) DeepCopy() *CiliumClusterMeshConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnabler) DeepCopyInto(out *CiliumClusterMeshEnabler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnabler.
func (in *CiliumClusterMeshEnabler) DeepCopy() *CiliumClusterMeshEnabler {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnabler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumClusterMeshEnabler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerInitParameters) DeepCopyInto(out *CiliumClusterMeshEnablerInitParameters) {
	*out = *in
	if in.EnableExternalWorkloads != nil {
		in, out := &in.EnableExternalWorkloads, &out.EnableExternalWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.EnableKvStoreMesh != nil {
		in, out := &in.EnableKvStoreMesh, &out.EnableKvStoreMesh
		*out = new(bool)
		**out = **in
	}
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerInitParameters.
func (in *CiliumClusterMeshEnablerInitParameters) DeepCopy() *CiliumClusterMeshEnablerInitParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerList) DeepCopyInto(out *CiliumClusterMeshEnablerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiliumClusterMeshEnabler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerList.
func (in *CiliumClusterMeshEnablerList) DeepCopy() *CiliumClusterMeshEnablerList {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiliumClusterMeshEnablerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerObservation) DeepCopyInto(out *CiliumClusterMeshEnablerObservation) {
	*out = *in
	if in.EnableExternalWorkloads != nil {
		in, out := &in.EnableExternalWorkloads, &out.EnableExternalWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.EnableKvStoreMesh != nil {
		in, out := &in.EnableKvStoreMesh, &out.EnableKvStoreMesh
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerObservation.
func (in *CiliumClusterMeshEnablerObservation) DeepCopy() *CiliumClusterMeshEnablerObservation {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerParameters) DeepCopyInto(out *CiliumClusterMeshEnablerParameters) {
	*out = *in
	if in.EnableExternalWorkloads != nil {
		in, out := &in.EnableExternalWorkloads, &out.EnableExternalWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.EnableKvStoreMesh != nil {
		in, out := &in.EnableKvStoreMesh, &out.EnableKvStoreMesh
		*out = new(bool)
		**out = **in
	}
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(string)
		**out = **in
	}
	if in.Wait != nil {
		in, out := &in.Wait, &out.Wait
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerParameters.
func (in *CiliumClusterMeshEnablerParameters) DeepCopy() *CiliumClusterMeshEnablerParameters {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerSpec) DeepCopyInto(out *CiliumClusterMeshEnablerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerSpec.
func (in *CiliumClusterMeshEnablerSpec) DeepCopy() *CiliumClusterMeshEnablerSpec {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumClusterMeshEnablerStatus) DeepCopyInto(out *CiliumClusterMeshEnablerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumClusterMeshEnablerStatus.
func (in *CiliumClusterMeshEnablerStatus) DeepCopy() *CiliumClusterMeshEnablerStatus {
	if in == nil {
		return nil
	}
	out := new(CiliumClusterMeshEnablerStatus)
	in.DeepCopyInto(out)
	return out
}
