apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-cilium
  annotations:
    meta.crossplane.io/maintainer: Joseph Ligier
    meta.crossplane.io/source: github.com/littlejo/provider-cilium
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The Cilium provider enables management of Cilium Cluster Mesh deployments and observability.    
